    
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
matrix:
  include:
  - os: linux
    env: BADGE=linux
  - os: osx
    env: BADGE=osx

  
language: R
sudo: false
cache: packages

script:
- R CMD build .
- R CMD check *tar.gz --as-cran
