matrix:
  include:
  - os: linux
    env: BADGE=linux
  - os: osx
    env: BADGE=osx

  
language: R
sudo: false
cache: packages

script:
- R CMD build .
- R CMD check *tar.gz --as-cran
- R CMD INSTALL . --build


before_deploy:
  - PKG_VER=${awk -F': ' '$1=="Version"{print $2;exit}' DESCRIPTION)
  - git config --local user.name "caiohamamura"
  - git config --local user.email "caiohamamura@gmail.com"
  - export TRAVIS_TAG=v${PKG_VER}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$TRAVIS_TOKEN"
  file_glob: true
  file: "radarBoxplot_${PKG_VER}*"
  skip_cleanup: true