matrix:
  include:
  - os: linux
    env: BADGE=linux
  - os: osx
    env: BADGE=osx

  
language: R
sudo: false
cache: packages

script:
- R CMD build .
- R CMD check *tar.gz --as-cran
- R CMD INSTALL . --build


deploy:
  provider: releases
  api_key: "$TRAVIS_TOKEN"
  file_glob: true
  file: "radarBoxplot_${PKG_VER}*"
  skip_cleanup: true